name: codex
description: 'A Comic Reading App.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  file_picker: ^8.1.4
  archive: ^3.6.1
  path: ^1.9.1
  path_provider: ^2.1.3
  xml: ^6.5.0
  pdfx: ^2.6.0
  shared_preferences: ^2.5.3
  gal: ^2.3.2
  share_plus: ^10.0.0
  image: ^4.1.0
  exif: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: 'assets/icon/app_icon.png'
  adaptive_icon_background: '@color/ic_launcher_background'
  adaptive_icon_foreground: 'assets/icon/app_icon.png'
  min_sdk_android: 21
